#!/bin/sh

if [ $# -eq 0 ]
then
	echo "no arguments"
	exit
fi

curl -fsSLo temp $2

MD5SUM="$(md5sum temp | cut -d ' ' -f 1)"
MD5="('$MD5SUM')"
SHA1SUM="$(sha1sum temp | cut -d ' ' -f 1)"
SHA1="('$SHA1SUM')"
SHA256SUM="$(sha256sum temp | cut -d ' ' -f 1)"
SHA256="('$SHA256SUM')"
SHA224SUM="$(sha224sum temp | cut -d ' ' -f 1)"
SHA224="('$SHA224SUM')"
SHA384SUM="$(sha384sum temp | cut -d ' ' -f 1)"
SHA384="('$SHA384SUM')"
SHA512SUM="$(sha512sum temp | cut -d ' ' -f 1)"
SHA512="('$SHA512SUM')"
B2SUM="$(b2sum temp | cut -d ' ' -f 1)"
B2="('$B2SUM')"
SOURCE="('$2')"

sed -i "s/pkgver=.*/pkgver=$1/" PKGBUILD > /dev/null
sed -i "s/md5sums=.*/md5sums=$MD5/" PKGBUILD > /dev/null
sed -i "s/sha1sums=.*/sha1sums=$SHA1/" PKGBUILD > /dev/null
sed -i "s/sha256sums=.*/sha256sums=$SHA256/" PKGBUILD > /dev/null
sed -i "s/sha224sums=.*/sha224sums=$SHA224/" PKGBUILD > /dev/null
sed -i "s/sha384sums=.*/sha384sums=$SHA384/" PKGBUILD > /dev/null
sed -i "s/sha512sums=.*/sha512sums=$SHA512/" PKGBUILD > /dev/null
sed -i "s/b2sums=.*/b2sums=$B2/" PKGBUILD > /dev/null
sed -i "s|source=.*|source=$SOURCE|" PKGBUILD > /dev/null

rm temp